sudo: false
services:
  - postgresql
env:
  global:
    - PG_PORT=5433
addons:
  postgresql: "12"

language: node_js
node_js:
  - 10.16.2
install:
  - npm install
before_script:
  - psql -c 'create database teamworkdb;' -U postgres
  - psql -c "CREATE DATABASE tw_testing;" -U postgres
script:
  - npm test
after_success:
  - npm run coverage