sudo: false
services:
  - postgresql
addons:
  postgresql: "12"
  
language: node_js
node_js:
  - 10.16.2
install:
  - npm install
before_script:
- psql -c 'CREATE DATABASE teamworkdb;' -U postgres
- psql -c "CREATE DATABASE tw_testing;" -U postgres
- psql -c "CREATE ROLE gbrian WITH LOGIN ENCRYPTED PASSWORD 'Sangwa@1998';" -U postgres
script:
  - npm test
after_success:
  - npm run coverage